-   id: check-parameters-typing
    name: check for existing of parameters typing
    description: prevents python files be commited if there is no typing in new functions/methods.
    entry: check-parameters-typing
    language: python
    types: [python]
