-   id: check-requirements-versions
    name: warning about requirements.txt
    description: makes sure all requirements have versions provided.
    entry: check-requirements-versions
    language: python
    files: requirements.*\.txt$