-   id: check-requirements-versions
    name: checks requirements versions
    description: makes sure all requirements have versions provided.
    entry: check-requirements-versions
    language: python
    files: requirements.*\.txt$