repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: /home/marcin/PycharmProjects/useful_pre_commit_hooks
    rev: 1.0.1
    hooks:
        - id: check-parameters-typing
